function [data, col] = defData(study)

data.labels = {...
    '1: Trial number overall (for this participant in total study'...
    '2: Trial number in this block'...
    '3: Trial number of this POM against this player'...
    '4: Block number'...
    '5: Participant number'...
    '6: Other player number'...
    '7: OUich (1 = me OU, other LR; 0 = me LR, other OU)'...
    '8: Which POM (1-20)'...
    '9: T for that trial'...
    '10: R for that trial'...
    '11: P for that trial'...
    '12: S for that trial'...
    '13: Whether player pressed a button that trial (1 = yes, 0 = no)'...
    '14: Type of button press (1 = valid, 2 = invalid, 3 = none)'...
    '15: Reaction time (of valid button press if multiple buttons pressed)'...
    '16: Response for that trial (1 = left, 2 = up, 3 = right, 4 = down)'...
    '17: Cooperate (1) or defect (0) on that trial'...
    '18: Other player"s response for that trial'...
    '19: Other cooperate (1) or defect (0) on that trial'...
    '20: Outcome on this trial (1 = CC, 2 = CD, 3 = DC, 4 = DD)'...
    '21: Participant points that trial'...
    '22: Other points that trial'...
    '23: Randomly selected trial from that interaction used for later payoff'...
    };

data.values = NaN(length(study.POM.val)*study.trials, length(data.labels));
% All column names are for participants, unless specified (e.g., IDother)
col.trialOverall    = 1;
col.trialBlock      = 2;
col.trialPOM        = 3;
col.block           = 4;
col.ID              = 5;
col.IDother         = 6;
col.OUich           = 7;
col.POM             = 8;
col.T               = 9;
col.R               = 10;
col.P               = 11;
col.S               = 12;
col.press           = 13;
col.pressType       = 14;
col.RT              = 15;
col.response        = 16;
col.CorD            = 17;
col.responseOther   = 18;
col.CorDOther       = 19;
col.outcome         = 20;
col.points          = 21;
col.pointsOther     = 22;
col.payoff          = 23;

end